markdown: kramdown
permalink: /:year/:month/:day/:title
url: http://zhoukeke.com
highlighter: rouge
name: 生命不息奋斗不止
description: 个人博客，写一些学习和工作上的经验
author: 周可可
email: zk90@vip.qq.com
weibo: 1674258120
hub: zk90
safe: false
gems: [jekyll-paginate]
paginate: 10
about: "测试"
comment: true
#uyan: 
#    uid: 2105226
duoshuo: 
    shortname: zk90